# Generated by Django 5.1.1 on 2024-09-30 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewsession',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='interviewsession',
            old_name='score',
            new_name='overall_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='difficulty_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_app.interviewsession'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='interview_answers/')),
                ('transcription', models.TextField(blank=True)),
                ('emotion_analysis', models.JSONField(default=dict)),
                ('correctness_score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interview_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='FacialAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('primary_emotion', models.CharField(max_length=20)),
                ('emotion_details', models.JSONField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_analyses', to='interview_app.answer')),
            ],
        ),
    ]
